//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 *
 */
public class FirstPassVisitor extends DepthFirstVisitor {

    int pc = 1;
    public HashMap<String, Integer> lblMap = new HashMap<String, Integer>();

    /**
     * f0 -> "MAIN"
     * f1 -> StmtList()
     * f2 -> "END"
     * f3 -> ( Procedure() )*
     * f4 -> <EOF>
     */
    @Override public void visit(Goal n) {
        pc = 1; 
        n.f0.accept(this);
        n.f1.accept(this); 
        n.f2.accept(this);
        n.f3.accept(this); 
        n.f4.accept(this);
    }

    /**
     * f0 -> ( ( Label() )? Stmt() )*
     */
    @Override public void visit(StmtList n) { 
        if (n.f0.present()) {
            for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements();) {
                Node node = e.nextElement();
                NodeSequence seq = (NodeSequence) node;
                Node stmt = seq.nodes.elementAt(1);
                NodeOptional labelOpt = (NodeOptional) seq.nodes.elementAt(0);

                if (labelOpt.present()) {
                    Label lbl = (Label) labelOpt.node;
                    lblMap.put(lbl.f0.toString(), pc);
                }
                
                stmt.accept(this); 
            }
        }
    }

    /**
     * f0 -> Label()
     * f1 -> "["
     * f2 -> IntegerLiteral()
     * f3 -> "]"
     * f4 -> StmtExp()
     */
    @Override public void visit(Procedure n) {
        pc = 1; 
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this); 
    }

    /**
     * f0 -> NoOpStmt()
     * | ErrorStmt()
     * | CJumpStmt()
     * | JumpStmt()
     * | HStoreStmt()
     * | HLoadStmt()
     * | MoveStmt()
     * | PrintStmt()
     */
    @Override public void visit(Stmt n) {
        n.f0.accept(this);
        pc++; 
    }


    /**
     * f0 -> "BEGIN"
     * f1 -> StmtList()
     * f2 -> "RETURN"
     * f3 -> SimpleExp()
     * f4 -> "END"
     */
    @Override public void visit(StmtExp n) {
        n.f0.accept(this);
        n.f1.accept(this); 
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        pc++; 
    }


}