//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Goal n, A argu);

   /**
    * <PRE>
    * f0 -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public void visit(StmtList n, A argu);

   /**
    * <PRE>
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    * </PRE>
    */
   public void visit(Procedure n, A argu);

   /**
    * <PRE>
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    * </PRE>
    */
   public void visit(Stmt n, A argu);

   /**
    * <PRE>
    * f0 -> "NOOP"
    * </PRE>
    */
   public void visit(NoOpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "ERROR"
    * </PRE>
    */
   public void visit(ErrorStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    * </PRE>
    */
   public void visit(CJumpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "JUMP"
    * f1 -> Label()
    * </PRE>
    */
   public void visit(JumpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    * </PRE>
    */
   public void visit(HStoreStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    * </PRE>
    */
   public void visit(HLoadStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    * </PRE>
    */
   public void visit(MoveStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public void visit(PrintStmt n, A argu);

   /**
    * <PRE>
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public void visit(Exp n, A argu);

   /**
    * <PRE>
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    * </PRE>
    */
   public void visit(StmtExp n, A argu);

   /**
    * <PRE>
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    * </PRE>
    */
   public void visit(Call n, A argu);

   /**
    * <PRE>
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public void visit(HAllocate n, A argu);

   /**
    * <PRE>
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    * </PRE>
    */
   public void visit(BinOp n, A argu);

   /**
    * <PRE>
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    * </PRE>
    */
   public void visit(Operator n, A argu);

   /**
    * <PRE>
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public void visit(SimpleExp n, A argu);

   /**
    * <PRE>
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    * </PRE>
    */
   public void visit(Temp n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public void visit(IntegerLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Label n, A argu);

}

