//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import java.util.stream.Collectors;
/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class SecondPassVisitor<R,A> extends GJDepthFirst<R,A> {

    public static class Nodes {

        public Set<Integer> def = new HashSet<>();
        public Set<Integer> use = new HashSet<>();
        public Set<Integer> in = new HashSet<>();
        public Set<Integer> out = new HashSet<>();
        public Set<Integer> succ = new HashSet<>();

        public Nodes() {
        }

        public Nodes(HashSet<Integer> def, HashSet<Integer> use) {
            this();
            this.def = def;
            this.use = use;
        }

        public void addSucc(Integer n) {
            if(n == null) return;
            this.succ.add(n);
        }

        public void addDef(Integer n) {
            if(n == null) return;
            this.def.add(n);
        }

        public void addUse(Integer n) {
            if(n == null) return;
            this.use.add(n);
        }
    }

    public static class CFG {

        public TreeMap<Integer, Nodes> nodes = new TreeMap<>();
        public TreeMap<Integer, Pair> liveRanges = new TreeMap<>();
        public TreeMap<Integer, String> alloc_t = new TreeMap<>();
        public TreeMap<Integer, Integer> spilled_t = new TreeMap<>();

        int spillcnt;
        int args_max;
        int offset_temps;
        boolean hasCall;
        int excess_args;
        int offset_t;

        public CFG() {
        }

        public CFG(int maxArgs, boolean hasCalls) {
            this();
            this.args_max = maxArgs;
            this.hasCall = hasCalls;
        }

        public void add(int i, Nodes n) {
            if(i < 0 || n == null) return;
            this.nodes.put(i, n);
        }

    }
    public static class Pair {
        public Integer start;
        public Integer end;

        public Pair(Integer s, Integer e) {
            this.start = s;
            this.end = e;
        }
    }

   
    public List<CFG> cfgs = new ArrayList<>();
    public Map<String, Integer> lblMap;
    CFG cfg;
    int pc;
    public SecondPassVisitor(HashMap<String, Integer> lm) {
        if (lm == null) {
            this.lblMap = new HashMap<>();
        } else {
            this.lblMap = new HashMap<>(lm);
        }
    }


    private void liveness(List<CFG> cfgs) {
        for (CFG cfg : cfgs) {
            boolean notdone = true;
            while (notdone) {
                notdone = false;

                for (Map.Entry<Integer, Nodes> entry : cfg.nodes.descendingMap().entrySet()) {
                    Integer ins = entry.getKey();
                    Nodes ns = entry.getValue();

                    HashSet<Integer> out1 = new HashSet<>();
                    for (Integer succ_ins : ns.succ) {
                        Nodes succ_ns = cfg.nodes.get(succ_ins);
                        if (succ_ns != null) {
                            out1.addAll(succ_ns.in);
                        }
                    }

                    HashSet<Integer> in1 = new HashSet<>(ns.use);
                    HashSet<Integer> tempOut = new HashSet<>(out1);
                    tempOut.removeAll(ns.def);
                    in1.addAll(tempOut);

                    if (!ns.out.equals(out1)) {
                        notdone = true;
                        ns.out.clear();
                        ns.out.addAll(out1);
                    }

                    if (!ns.in.equals(in1)) {
                        notdone = true;
                        ns.in.clear();
                        ns.in.addAll(in1);
                    }
                }
            }
        }
    }

    private void computelive(List<CFG> cfgs) {
        for (CFG cfg : cfgs) {
            for (Map.Entry<Integer, Nodes> entry : cfg.nodes.entrySet()) {
                Integer ins = entry.getKey();
                Nodes ns = entry.getValue();

                Set<Integer> combinedLiveSet = new HashSet<>(ns.in);
                combinedLiveSet.addAll(ns.out);

                for (Integer live_var : combinedLiveSet) {
                    extendLiveRange(cfg, live_var, ins);
                }
            }
        }
    }

    private void extendLiveRange(CFG cfg, Integer var, Integer ins) {
        Pair range = cfg.liveRanges.get(var);

        if (range != null) {
            range.start = Math.min(range.start, ins);
            range.end = Math.max(range.end, ins);
        } else {
            cfg.liveRanges.put(var, new Pair(ins, ins));
        }
    }

    private void scan_linear(List<CFG> cfgs) {
        for (CFG cfg : cfgs) {
            List<Map.Entry<Integer, Pair>> intervals = new ArrayList<>(cfg.liveRanges.entrySet());
            intervals.sort(Comparator.comparingInt(e -> e.getValue().start));

            List<Map.Entry<Integer, Pair>> active = new ArrayList<>();
            Queue<String> free_regs = new LinkedList<>(Arrays.asList(
                "t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7",
                "s0", "s1", "s2", "s3", "s4", "s5", "s6",
                "t8", "t9"
            ));

            for (Map.Entry<Integer, Pair> entry : intervals) {
                expire_inactive(entry, active, free_regs, cfg);
                allocateOrSpillInterval(entry, active, free_regs, cfg);
            }
        }
    }

    private void expire_inactive(Map.Entry<Integer, Pair> entry,
                                         List<Map.Entry<Integer, Pair>> active,
                                         Queue<String> free_regs,
                                         CFG cfg) {
        int intervalStart = entry.getValue().start;

        active.removeIf(act_entry -> {
            boolean expired = act_entry.getValue().end < intervalStart;
            if (expired) {
                String reg_free = cfg.alloc_t.get(act_entry.getKey());
                free_regs.add(reg_free);
            }
            return expired;
        });
    }

    private void allocateOrSpillInterval(Map.Entry<Integer, Pair> entry,
                                         List<Map.Entry<Integer, Pair>> active,
                                         Queue<String> free_regs,
                                         CFG cfg) {

        int i = entry.getKey();
        Pair interval = entry.getValue();

        if (!free_regs.isEmpty()) {
            String new_reg = free_regs.poll();
            cfg.alloc_t.put(i, new_reg);
            active.add(entry);
            active.sort(Comparator.comparingInt(e -> e.getValue().end));
        } else {
            Map.Entry<Integer, Pair> spill = active.get(active.size() - 1);

            boolean spillCurrent = interval.end >= spill.getValue().end;

            if (spillCurrent) {
                cfg.spillcnt++;
                cfg.spilled_t.put(i, cfg.spillcnt);
            } else {
                cfg.alloc_t.put(i, cfg.alloc_t.get(spill.getKey()));
                cfg.alloc_t.remove(spill.getKey());

                cfg.spillcnt++;
                cfg.spilled_t.put(spill.getKey(), cfg.spillcnt);

                active.remove(spill);
                active.add(entry);
                active.sort(Comparator.comparingInt(e -> e.getValue().end));
            }
        }
    }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   @Override public R visit(Goal n, A argu) {
      R _ret=null;
      pc=1;
      cfg=new CFG();
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      cfg.offset_t=0;
      cfgs.add(cfg);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      liveness(cfgs);
      computelive(cfgs);
      scan_linear(cfgs);
      // printCFGs(cfgs);
      return _ret;
   }


   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
  @Override public R visit(Procedure n, A argu) {
      R _ret=null;
      pc=1;
      cfg=new CFG();
      cfg.excess_args=Math.max(0,Integer.parseInt(n.f2.f0.toString())-4);
      cfg.offset_t=8+cfg.excess_args;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      cfgs.add(cfg);
      return _ret;
   }
   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    */
   @Override public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      pc++;
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   @Override public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Nodes ns=new Nodes();
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   @Override public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Nodes ns=new Nodes();
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   @Override public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      Nodes ns=new Nodes();
      n.f0.accept(this, argu);
      n.f1.accept(this, (A)ns);
      n.f2.accept(this, argu);
      ns.addSucc(pc+1);
      ns.addSucc(lblMap.get(n.f2.f0.toString()));
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
  @Override public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Nodes ns=new Nodes();
      ns.addSucc(lblMap.get(n.f1.f0.toString()));
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
  @Override public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      Nodes ns=new Nodes();
      n.f0.accept(this, argu);
      n.f1.accept(this, (A)ns);
      n.f2.accept(this, argu);
      n.f3.accept(this, (A)ns);
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
    @Override public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      Nodes ns=new Nodes();
      n.f0.accept(this, argu);
      ns.def.add(Integer.parseInt(n.f1.f1.f0.toString()));
      n.f2.accept(this, (A)ns);
      n.f3.accept(this, argu);
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
  @Override public R visit(MoveStmt n, A argu) {
      R _ret=null;
      Nodes ns=new Nodes();
      n.f0.accept(this, argu);
      ns.def.add(Integer.parseInt(n.f1.f1.f0.toString()));
      n.f2.accept(this, (A)ns);
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   @Override public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Nodes ns=new Nodes();
      n.f1.accept(this, (A)ns);
      ns.addSucc(pc+1);
      cfg.add(pc, ns);
      return _ret;
   }


   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
    @Override public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Nodes ns=new Nodes();
      n.f3.accept(this, (A)ns);
      ns.addSucc(-1);
      cfg.add(pc, ns);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
  @Override public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      cfg.hasCall=true;
      if(n.f3.present()){
         NodeListOptional nlo=n.f3;
         for(int i=0;i<nlo.nodes.size();i++){
            Node t=nlo.nodes.elementAt(i);
            t.accept(this, argu);
         }
         cfg.args_max=Math.max(cfg.args_max,nlo.nodes.size());
       }
      n.f4.accept(this, argu);
      return _ret;
   }


   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
    @Override public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Nodes ns=(Nodes)argu;
      ns.use.add(Integer.parseInt(n.f1.f0.toString()));
      return _ret;
   }


}