//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import visitor.SecondPassVisitor.CFG;
import visitor.SecondPassVisitor.Nodes;
import visitor.SecondPassVisitor.Pair;

public class ThirdPassVisitor<R,A> extends GJDepthFirst<R,A> {

   private boolean afterLabelPending = false;
   private void emitln(String s) {
      System.out.println(s);
      afterLabelPending = false;
   }
   //
  public List<CFG> cfgs;
  public ThirdPassVisitor(List<CFG> cfgs){
     if (cfgs == null) {
         this.cfgs = new ArrayList<>(cfgs);
     } else {
         this.cfgs = cfgs;
     }
   }
   int procedure_count = 0;
   boolean v0_available = true;
   CFG cfg;

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
  @Override public R visit(Goal n, A argu) {
      R _ret = null;
      cfg = cfgs.get(procedure_count);
      System.out.print("MAIN [0] [");
      int stackSlots;
      if (!cfg.hasCall) {
         stackSlots = cfg.spillcnt;
      } else {
         stackSlots = cfg.spillcnt + 10;
      }
      System.out.print(stackSlots);
      System.out.print("] [");
      System.out.print(cfg.args_max);
      System.out.println("]\n");
      n.f1.accept(this, argu);
      System.out.println("END\n");
      procedure_count++;
      n.f3.accept(this, argu);  
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   @Override public R visit(StmtList n, A argu) {
   R _ret = null;
   if (n.f0.present()) {
      for (Node node : n.f0.nodes) {
         NodeSequence label_stmt = (NodeSequence) node;
         NodeOptional label = (NodeOptional) label_stmt.nodes.elementAt(0);
         Node stmt = (Node) label_stmt.nodes.elementAt(1);

         if (label.present()) {
         // If the previous emitted thing was also a label (with no instruction),
         // insert a NOOP to keep MiniRA syntax valid.
         if (afterLabelPending) {
            emitln("NOOP");
         }
         Label lbl = (Label) label.node;
         String label_name = lbl.f0.toString();
         // Print the label line itself (DO NOT clear the pending flag here)
         System.out.println(label_name);
         afterLabelPending = true; // waiting for the next instruction after this label
         }

         // The statement may or may not emit any instruction lines.
         // All statement emission should use emitln(...). If it emits nothing,
         // afterLabelPending stays true, so the *next* label will trigger a NOOP.
         stmt.accept(this, argu);
      }
   }
   return _ret;
   }


   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
  @Override public R visit(Procedure n, A argu) {
      R _ret = null;
      cfg = cfgs.get(procedure_count);

      String procedureName = n.f0.f0.toString();
      String argsCountStr = n.f2.f0.toString();
      int numArgs = Integer.parseInt(argsCountStr);
      
      String s;
      int totalStackSlots;

      if (!cfg.hasCall) {
         totalStackSlots = cfg.spillcnt + 8 + cfg.excess_args;
         cfg.offset_temps = 7 + cfg.excess_args;
      } else {
         totalStackSlots = cfg.spillcnt + 18 + cfg.excess_args;
         cfg.offset_temps = 17 + cfg.excess_args;
      }

      s = procedureName + " [" + argsCountStr + "] [" + totalStackSlots + "] [" + cfg.args_max + "]\n";

      int it = 0;

      while(it <= 7) {
         s += "ASTORE SPILLEDARG " + (it + cfg.excess_args) + " s" + it + "\n";
         it++;
      }
      System.out.print(s);

      int temp_ind = 0;

      while (temp_ind < numArgs) {
         if (temp_ind <= 3) {
            String s1 = "MOVE ";
            if (cfg.alloc_t.containsKey(temp_ind)) {
               s1 += (String) cfg.alloc_t.get(temp_ind);
               s1 += " a" + temp_ind;
               System.out.println(s1);
            } else if (cfg.spilled_t.containsKey(temp_ind)) {
               int stack_pos = (Integer) cfg.spilled_t.get(temp_ind) + cfg.offset_temps;
               s1 += "v0 a" + temp_ind;
               System.out.println(s1);
               System.out.println("ASTORE SPILLEDARG " + stack_pos + " v0");
            }
         }
         temp_ind++;
      }

      it = 4;

      while (it < numArgs) {
         if (cfg.alloc_t.containsKey(it)) {
            System.out.println("ALOAD " + cfg.alloc_t.get(it) + " SPILLEDARG " + (it - 4));
         } else if (cfg.spilled_t.containsKey(it)) {
            cfg.spilled_t.put(it, it - 4);
         }
         it++;
      }

      n.f4.accept(this, argu);

      it = 0;

      while (it <= 7) {
         System.out.println("ALOAD s" + it + " SPILLEDARG " + (it + cfg.excess_args));
         it++;
      }
      System.out.println("END\n");

      procedure_count++;
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   @Override public R visit(NoOpStmt n, A argu) {
      System.out.println("NOOP\n");
      return null;
   }

   /**
    * f0 -> "ERROR"
    */
   @Override public R visit(ErrorStmt n, A argu) {
      System.out.println("ERROR\n");
      return null;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
  @Override public R visit(CJumpStmt n, A argu) {
      R _ret = null;
      String tempReg = (String) n.f1.accept(this, argu);
      String label = n.f2.f0.toString();
      String s = "CJUMP " + tempReg + " " + label;
      System.out.println(s);  
      v0_available = true;
      return _ret;
   }
   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   @Override public R visit(JumpStmt n, A argu) {
      String s="JUMP ";
      s+=n.f1.accept(this, argu);
      System.out.println(s);
      return null;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   @Override public R visit(HStoreStmt n, A argu) {
      String s="HSTORE ";
      s+=n.f1.accept(this, argu);
      s+=" "+n.f2.f0.toString();
      s+=" "+n.f3.accept(this, argu);
      System.out.println(s);
      v0_available=true;
      return null;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   @Override public R visit(HLoadStmt n, A argu) {
      R _ret = null;
      int temp_ind = Integer.parseInt(n.f1.f1.f0.toString());
      String baseReg = (String) n.f2.accept(this, argu);
      String offset = n.f3.f0.toString();
      String destReg;
      if (cfg.alloc_t.containsKey(temp_ind)) {
         destReg = (String) cfg.alloc_t.get(temp_ind);
         System.out.println("HLOAD " + destReg + " " + baseReg + " " + offset);
      } 
      else if (cfg.spilled_t.containsKey(temp_ind)) {
         destReg = "v0";
         int stack_pos = (Integer) cfg.spilled_t.get(temp_ind) + cfg.offset_temps;  
         System.out.println("HLOAD " + destReg + " " + baseReg + " " + offset);
         System.out.println("ASTORE SPILLEDARG " + stack_pos + " v0");
      }  
      v0_available = true;
      return _ret;
   }
   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
  @Override public R visit(MoveStmt n, A argu) {
      R _ret = null;
      String src = (String) n.f2.accept(this, argu);
      int temp_ind = Integer.parseInt(n.f1.f1.f0.toString());
      String destReg;
      if (cfg.alloc_t.containsKey(temp_ind)) {
         destReg = (String) cfg.alloc_t.get(temp_ind);
         System.out.println("MOVE " + destReg + " " + src);
      } 
      else if (cfg.spilled_t.containsKey(temp_ind)) {
         destReg = "v0";
         int stack_pos = (Integer) cfg.spilled_t.get(temp_ind) + cfg.offset_temps;  
         System.out.println("MOVE " + destReg + " " + src);
         System.out.println("ASTORE SPILLEDARG " + stack_pos + " v0");
      }  
      v0_available = true;
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   @Override public R visit(PrintStmt n, A argu) {
      String s="PRINT ";
      s+=n.f1.accept(this, argu);
      System.out.println(s);
      v0_available=true;
      return null;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   @Override public R visit(Exp n, A argu) {
      String s=(String)n.f0.accept(this, argu);
      return (R)s;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   @Override public R visit(StmtExp n, A argu) {
      n.f1.accept(this, argu);
      System.out.println("MOVE v0 "+n.f3.accept(this,argu));
      v0_available=true;
      return null;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
  @Override public R visit(Call n, A argu) {
      R _ret = null;
      int it = 0;
      while (it <= 9) {
         System.out.println("ASTORE SPILLEDARG " + (it + cfg.offset_t) + " t" + it);
         it++;
      }
      if (n.f3.present()) {
         int index = 0;
         for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            Node t = e.nextElement();
            String argValue = (String) t.accept(this, argu);
            if (index <= 3) {
               System.out.println("MOVE a" + index + " " + argValue);
            } else {
               System.out.println("PASSARG " + (index - 3) + " " + argValue);
            }
            index++;
         }
      }
      String funcName = (String) n.f1.accept(this, argu);
      System.out.println("CALL " + funcName);
      it = 0;
      while (it <= 9) {
         System.out.println("ALOAD t" + it + " SPILLEDARG " + (it + cfg.offset_t));
         it++;
      }
      _ret = (R) "v0";
      return _ret;
   }
   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   @Override public R visit(HAllocate n, A argu) {
      String s="HALLOCATE ";
      s+=n.f1.accept(this, argu);
      v0_available=true;
      return (R)s;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   @Override public R visit(BinOp n, A argu) {
      String s=(String)n.f0.accept(this, argu);
      s+=" "+n.f1.accept(this, argu);
      s+=" "+n.f2.accept(this, argu);
      v0_available=true;
      return (R)s;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   @Override public R visit(Operator n, A argu) {
      String s=(String) n.f0.choice.toString();
      return (R)s;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   @Override public R visit(SimpleExp n, A argu) {
      String s=(String) n.f0.accept(this, argu);
      return (R)s;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
  @Override public R visit(Temp n, A argu) {
      R _ret = null;
      String s;
      int temp_ind = Integer.parseInt(n.f1.f0.toString());
      if (!cfg.alloc_t.containsKey(temp_ind)) {
         int stack_pos = (Integer) cfg.spilled_t.get(temp_ind) + cfg.offset_temps;  
         if (!v0_available) {
            s = "v1";
            System.out.println("ALOAD v1 SPILLEDARG " + stack_pos);
            v0_available = true; 
         } else {
            s = "v0";
            System.out.println("ALOAD v0 SPILLEDARG " + stack_pos);
            v0_available = false;
         }
      } else {
         s = (String) cfg.alloc_t.get(temp_ind);
      }  
      _ret = (R) s;
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   @Override public R visit(IntegerLiteral n, A argu) {
      String s=(String)n.f0.toString();
      return (R)s;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   @Override public R visit(Label n, A argu) {
      String s=(String)n.f0.toString();
      return (R)s;
   }

}
