//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> &lt;EOF&gt;
    * </PRE>
    */
   public R visit(Goal n);

   /**
    * <PRE>
    * f0 -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public R visit(StmtList n);

   /**
    * <PRE>
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * </PRE>
    */
   public R visit(Procedure n);

   /**
    * <PRE>
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    * </PRE>
    */
   public R visit(Stmt n);

   /**
    * <PRE>
    * f0 -> "NOOP"
    * </PRE>
    */
   public R visit(NoOpStmt n);

   /**
    * <PRE>
    * f0 -> "ERROR"
    * </PRE>
    */
   public R visit(ErrorStmt n);

   /**
    * <PRE>
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    * </PRE>
    */
   public R visit(CJumpStmt n);

   /**
    * <PRE>
    * f0 -> "JUMP"
    * f1 -> Label()
    * </PRE>
    */
   public R visit(JumpStmt n);

   /**
    * <PRE>
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    * </PRE>
    */
   public R visit(HStoreStmt n);

   /**
    * <PRE>
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    * </PRE>
    */
   public R visit(HLoadStmt n);

   /**
    * <PRE>
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    * </PRE>
    */
   public R visit(MoveStmt n);

   /**
    * <PRE>
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public R visit(PrintStmt n);

   /**
    * <PRE>
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    * </PRE>
    */
   public R visit(ALoadStmt n);

   /**
    * <PRE>
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    * </PRE>
    */
   public R visit(AStoreStmt n);

   /**
    * <PRE>
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    * </PRE>
    */
   public R visit(PassArgStmt n);

   /**
    * <PRE>
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public R visit(CallStmt n);

   /**
    * <PRE>
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public R visit(Exp n);

   /**
    * <PRE>
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public R visit(HAllocate n);

   /**
    * <PRE>
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    * </PRE>
    */
   public R visit(BinOp n);

   /**
    * <PRE>
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    * </PRE>
    */
   public R visit(Operator n);

   /**
    * <PRE>
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    * </PRE>
    */
   public R visit(SpilledArg n);

   /**
    * <PRE>
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public R visit(SimpleExp n);

   /**
    * <PRE>
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    * </PRE>
    */
   public R visit(Reg n);

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public R visit(IntegerLiteral n);

   /**
    * <PRE>
    * f0 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public R visit(Label n);

   /**
    * <PRE>
    * f0 -> "//"
    * f1 -> SpillStatus()
    * </PRE>
    */
   public R visit(SpillInfo n);

   /**
    * <PRE>
    * f0 -> &lt;SPILLED&gt;
    *       | &lt;NOTSPILLED&gt;
    * </PRE>
    */
   public R visit(SpillStatus n);

}

