//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> &lt;EOF&gt;
    * </PRE>
    */
   public R visit(Goal n, A argu);

   /**
    * <PRE>
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    * </PRE>
    */
   public R visit(ImportFunction n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    * </PRE>
    */
   public R visit(MainClass n, A argu);

   /**
    * <PRE>
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    * </PRE>
    */
   public R visit(TypeDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    * </PRE>
    */
   public R visit(ClassDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    * </PRE>
    */
   public R visit(ClassExtendsDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    * </PRE>
    */
   public R visit(VarDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    * </PRE>
    */
   public R visit(MethodDeclaration n, A argu);

   /**
    * <PRE>
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    * </PRE>
    */
   public R visit(FormalParameterList n, A argu);

   /**
    * <PRE>
    * f0 -> Type()
    * f1 -> Identifier()
    * </PRE>
    */
   public R visit(FormalParameter n, A argu);

   /**
    * <PRE>
    * f0 -> ","
    * f1 -> FormalParameter()
    * </PRE>
    */
   public R visit(FormalParameterRest n, A argu);

   /**
    * <PRE>
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    * </PRE>
    */
   public R visit(Type n, A argu);

   /**
    * <PRE>
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    * </PRE>
    */
   public R visit(ArrayType n, A argu);

   /**
    * <PRE>
    * f0 -> "boolean"
    * </PRE>
    */
   public R visit(BooleanType n, A argu);

   /**
    * <PRE>
    * f0 -> "int"
    * </PRE>
    */
   public R visit(IntegerType n, A argu);

   /**
    * <PRE>
    * f0 -> "Function"
    * f1 -> "&lt;"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> "&gt;"
    * </PRE>
    */
   public R visit(LambdaType n, A argu);

   /**
    * <PRE>
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    * </PRE>
    */
   public R visit(Statement n, A argu);

   /**
    * <PRE>
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    * </PRE>
    */
   public R visit(Block n, A argu);

   /**
    * <PRE>
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    * </PRE>
    */
   public R visit(AssignmentStatement n, A argu);

   /**
    * <PRE>
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    * </PRE>
    */
   public R visit(ArrayAssignmentStatement n, A argu);

   /**
    * <PRE>
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    * </PRE>
    */
   public R visit(IfStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * </PRE>
    */
   public R visit(IfthenStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    * </PRE>
    */
   public R visit(IfthenElseStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * </PRE>
    */
   public R visit(WhileStatement n, A argu);

   /**
    * <PRE>
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    * </PRE>
    */
   public R visit(PrintStatement n, A argu);

   /**
    * <PRE>
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    * </PRE>
    */
   public R visit(Expression n, A argu);

   /**
    * <PRE>
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "-&gt;"
    * f4 -> Expression()
    * </PRE>
    */
   public R visit(LambdaExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(AndExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(OrExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "&lt;="
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(CompareExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(neqExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(AddExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(MinusExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(TimesExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public R visit(DivExpression n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    * </PRE>
    */
   public R visit(ArrayLookup n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    * </PRE>
    */
   public R visit(ArrayLength n, A argu);

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    * </PRE>
    */
   public R visit(MessageSend n, A argu);

   /**
    * <PRE>
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    * </PRE>
    */
   public R visit(ExpressionList n, A argu);

   /**
    * <PRE>
    * f0 -> ","
    * f1 -> Expression()
    * </PRE>
    */
   public R visit(ExpressionRest n, A argu);

   /**
    * <PRE>
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    * </PRE>
    */
   public R visit(PrimaryExpression n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public R visit(IntegerLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> "true"
    * </PRE>
    */
   public R visit(TrueLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> "false"
    * </PRE>
    */
   public R visit(FalseLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public R visit(Identifier n, A argu);

   /**
    * <PRE>
    * f0 -> "this"
    * </PRE>
    */
   public R visit(ThisExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    * </PRE>
    */
   public R visit(ArrayAllocationExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    * </PRE>
    */
   public R visit(AllocationExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "!"
    * f1 -> Expression()
    * </PRE>
    */
   public R visit(NotExpression n, A argu);

   /**
    * <PRE>
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    * </PRE>
    */
   public R visit(BracketExpression n, A argu);

}
