//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Goal n, A argu);

   /**
    * <PRE>
    * f0 -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public void visit(StmtList n, A argu);

   /**
    * <PRE>
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * </PRE>
    */
   public void visit(Procedure n, A argu);

   /**
    * <PRE>
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    * </PRE>
    */
   public void visit(Stmt n, A argu);

   /**
    * <PRE>
    * f0 -> "NOOP"
    * </PRE>
    */
   public void visit(NoOpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "ERROR"
    * </PRE>
    */
   public void visit(ErrorStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    * </PRE>
    */
   public void visit(CJumpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "JUMP"
    * f1 -> Label()
    * </PRE>
    */
   public void visit(JumpStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    * </PRE>
    */
   public void visit(HStoreStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    * </PRE>
    */
   public void visit(HLoadStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    * </PRE>
    */
   public void visit(MoveStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public void visit(PrintStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    * </PRE>
    */
   public void visit(ALoadStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    * </PRE>
    */
   public void visit(AStoreStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    * </PRE>
    */
   public void visit(PassArgStmt n, A argu);

   /**
    * <PRE>
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public void visit(CallStmt n, A argu);

   /**
    * <PRE>
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public void visit(Exp n, A argu);

   /**
    * <PRE>
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    * </PRE>
    */
   public void visit(HAllocate n, A argu);

   /**
    * <PRE>
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    * </PRE>
    */
   public void visit(BinOp n, A argu);

   /**
    * <PRE>
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    * </PRE>
    */
   public void visit(Operator n, A argu);

   /**
    * <PRE>
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    * </PRE>
    */
   public void visit(SpilledArg n, A argu);

   /**
    * <PRE>
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public void visit(SimpleExp n, A argu);

   /**
    * <PRE>
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    * </PRE>
    */
   public void visit(Reg n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public void visit(IntegerLiteral n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Label n, A argu);

   /**
    * <PRE>
    * f0 -> "//"
    * f1 -> SpillStatus()
    * </PRE>
    */
   public void visit(SpillInfo n, A argu);

   /**
    * <PRE>
    * f0 -> &lt;SPILLED&gt;
    *       | &lt;NOTSPILLED&gt;
    * </PRE>
    */
   public void visit(SpillStatus n, A argu);

}

